language: android

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

android:
  components:
    - tools
    - build-tools-28.0.0
    - android-28
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew leak-app:assembleRelease

